---
# tasks file for roles/common

- name: update all of the installed packages
  yum:
    name: "*"
    state: "latest"
    update_cache: "yes"

- name: Ensure EPEL is enabled 
  yum: 
    name: epel-release 
    state: present 

- name: make sure firewalld is disabled and masked (causes MANY issues with the cluster)
  systemd:
    name: firewalld
    enabled: no
    state: stopped
    masked: yes

- name: just force systemd to reread configs (2.4 and above)
  systemd: daemon_reload=yes

- name: install the common packages
  yum:
    name: "{{ common_packages }}"
    state: "installed"
  with_items: "{{ common_packages }}"


- name: Start and Enable iptables
  systemd:
    name: iptables
    enabled: yes
    masked: no
    state: started
